# =========================================
# APPLICATION
# =========================================
spring.application.name=cloud.platform

# =========================================
# SERVER
# =========================================
server.port=8080

# =========================================
# POSTGRESQL DATASOURCE
# =========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_platform
spring.datasource.username=postgres
spring.datasource.password=2002
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================
# JPA / HIBERNATE
# =========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================================
# LOGGING SQL
# =========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.security=INFO

# =========================================
# JACKSON
# =========================================
spring.jackson.serialization.indent-output=true

# =========================================
# ERROR HANDLING
# =========================================
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
spring.main.allow-bean-definition-overriding=true

# =========================================
# DEVTOOLS
# =========================================
spring.devtools.restart.enabled=true

# =========================================
# JWT
# =========================================
jwt.secret=QmFzZTY0U2VjcmV0S2V5VmFsdWVIZXJlMTIzNDU2Nzg5
jwt.expiration=3600000
jwt.refresh-expiration=604800000