# =========================================
# APPLICATION
# =========================================
spring.application.name=app
# =========================================
# SERVER
# =========================================
server.port=8080

# =========================================
# MYSQL DATASOURCE
# =========================================
spring.datasource.url=jdbc:mysql://localhost:3306/userdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================
# JPA / HIBERNATE
# =========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# =========================================
# LOGGING SQL
# =========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.security=INFO


# =========================================
# JACKSON
# =========================================
spring.jackson.serialization.indent-output=true

# =========================================
# VALIDATION
# =========================================
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true



# =========================================
# DEVTOOLS
# =========================================
spring.devtools.restart.enabled=true

jwt.secret=QmFzZTY0U2VjcmV0S2V5VmFsdWVIZXJlMTIzNDU2Nzg5
jwt.expiration=3600000
jwt.refresh-expiration=604800000